### ISSUE TITLE
SyntaxError during Python 3.4 installation

### ISSUE THREAD

**Issue by vmarkovtsev** [google/py-gfm#19]
```sudo pip3 install py-gfm```

results in

```
Installing collected packages: py-gfm, unittest2, argparse, traceback2, linecache2
  Running setup.py install for py-gfm
    
      File "/usr/local/lib/python3.4/dist-packages/gfm/autolink.py", line 42
        r'<>]+\)))*\)|[^\s`!()\[\]{};:' + r"'" + ur'".,<>?«»“”‘’]))'
                                                                   ^
    SyntaxError: invalid syntax
```
My Python is CPython 3.4.1.

**Comment by nex3** [comment]
I have no idea why this error is happening. Can someone with more Python experience chime in?

**Comment by ftzeng** [comment]
It's an issue with using `u` for unicode literals in Python 3. I just submitted a PR which fixes this (and another Python 3 import issue), hopefully it will be accepted soon.

Otherwise, you can install from my branch:

    pip install git+https://github.com/ftzeng/py-gfm@python3_fixes
