### ISSUE TITLE
unittest2 required?

### ISSUE THREAD

**Issue by joshkel** [google/py-gfm#24]
Why require unittest2 in setup.py? Wouldn't that better be handled by a `dev-requirements.txt` or similar, so that apps don't have to pull in unittest2 and its dependencies just to use py-gfm?

**Comment by nex3** [comment]
I'm mostly not a Python developer, so I'd imagine I copied it from somewhere. If that's not ideal, feel free to submit a pull request.

**Comment by joshkel** [comment]
I'm mostly not a Python developer either, which is why I wanted to run it by you before opening a PR, but I just submitted #25 to address this. Thanks.

**Comment by Zopieux** [comment]
#25 was merged, this issue can be closed.
